insert into users (name, login, password) values ('admin', 'admin', '$2a$10$7zUsHnbwiASdnEGyO31bweOZ0MqNSVJmy6rUahhSYqctojoIB01nu');
insert into users (name, login, password) values ('user', 'user', '$2a$10$7zUsHnbwiASdnEGyO31bweOZ0MqNSVJmy6rUahhSYqctojoIB01nu');

insert into user_roles (user_id, roles) values (1, 'ADMIN');
insert into user_roles (user_id, roles) values (2, 'USER');

insert into news (title, date, descr, image, user_id) values ('title1', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 1);
insert into news (title, date, descr, image, user_id) values ('title2', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title3', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title4', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title5', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title6', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title7', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title8', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title9', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title10', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title11', 'yesterday'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);

insert into news (title, date, descr, image, user_id) values ('title1', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 1);
insert into news (title, date, descr, image, user_id) values ('title2', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title3', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title4', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title5', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title6', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title7', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title8', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title9', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title10', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
insert into news (title, date, descr, image, user_id) values ('title11', 'today'::timestamp, 'We map a request with the showCities path to the controller''s findCities() method. The default request is a GET request. The model gains a list of cities and the processing is sent to the showCities.html Thymeleaf template file.', 'no-image.jpg', 2);
